import requests
from requests.auth import HTTPBasicAuth
import os

# Configuration
SN_URL = "https://dev273008.service-now.com"
SN_USER = "admin"
SN_PASS = "@nL=BMhj07Sk"
TABLE_NAME = "x_1941577_tee_se_0_ai_incident_demo"

def deploy_business_rule():
    print(f"Deploying AI Auto-Assignment Business Rule to {SN_URL}...")
    
    # Business Rule Script (JavaScript)
    br_script = """(function executeRule(current, previous /*null when async*/) {
    
    // Auto-assignment mapping
    var mapping = {
        'Network': 'Network Support',
        'Access': 'Identity & Access',
        'Hardware': 'Desktop Support'
    };
    
    if (current.category && mapping[current.category]) {
        var groupName = mapping[current.category];
        var grGroup = new GlideRecord('sys_user_group');
        if (grGroup.get('name', groupName)) {
            current.assignment_group = grGroup.getUniqueValue();
            gs.info('AI Auto-Assignment: Routed incident to ' + groupName);
        }
    }

})(current, previous);"""

    payload = {
        "name": "AI Auto-Assignment",
        "collection": TABLE_NAME,
        "when": "before",
        "action_insert": "true",
        "action_update": "true",
        "active": "true",
        "advanced": "true",
        "script": br_script,
        "description": "Automatically assigns groups based on AI-detected categories. Generated by Antigravity AI."
    }
    
    url = f"{SN_URL}/api/now/table/sys_script"
    
    try:
        response = requests.post(
            url,
            json=payload,
            auth=HTTPBasicAuth(SN_USER, SN_PASS),
            headers={"Content-Type": "application/json", "Accept": "application/json"}
        )
        
        if response.status_code == 201:
            print("Business Rule deployed successfully!")
            print(f"  Sys ID: {response.json()['result']['sys_id']}")
        else:
            print(f"Failed to deploy Business Rule: {response.status_code}")
            print(f"  Response: {response.text}")
            
    except Exception as e:
        print(f"Error: {e}")

if __name__ == "__main__":
    deploy_business_rule()
